version: 2

models:
  - name: streams
    columns:
      - name: id
        tests:
          - unique
          - not_null

      - name: datetime
        tests:
          - not_null


      - name: movie_id
        tests:
          - not_null

      - name: user_id
        tests:
          - not_null


